export enum ErrorCode {
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  WEBHOOK_PROVIDER_NOT_FOUND = "WEBHOOK_PROVIDER_NOT_FOUND",
  WEBHOOK_AUTHENTICATION_FAILED = "WEBHOOK_AUTHENTICATION_FAILED",
  MALFORMED_WEBHOOK_EVENT = "MALFORMED_WEBHOOK_EVENT",
}
